### ISSUE TITLE
what are the 12 parameters in SGM?

### ISSUE THREAD

**Issue by PKUCheng** [nianticlabs/depth-hints#2]
Hi! authors
what are the 12 parameters in SGM?
THX!

**Comment by JamieWatson683** [comment]
Hi,

The parameters we used are in the table below:

![image](https://user-images.githubusercontent.com/32708055/71720273-03bd0200-2e19-11ea-9b8a-a3e52e01bcfb.png)

Note that where there are multiple values per parameter we sweep over them to generate our depth hints. The code should be up soon (hoping early next week). 

Thanks,
Jamie
